site_name: AyasakiMoe Services
theme:
  logo: custom/logo.png
  name: material
  custom_dir: overrides
  language: zh
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-4
        name: 切换到黑夜
    - media: "(prefers-color-scheme: dark)"
      scheme: slate 
      toggle:
        icon: material/brightness-7
        name: 切换到白天
  features:
    - navigation.instant
    - navigation.tracking
    - search.suggest
    - search.highlight
    - search.share
    - header.autohide
extra_css:
  - custom/main.css
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/Akatsuki-Misaki
      name: Official.
    - icon: fontawesome/solid/envelope
      link: mailto:mirai@lolicon.team
      name: 联系赤月未咲 
plugins:
  - search
  - tags:
      tags_file: tags.md
copyright: Copyright &copy; 2021 - 2022 赤月未咲
repo_url: https://github.com/Akatsuki-Misaki
repo_name: AyasakiMoe/Docs-AyasakiMoe
edit_uri: edit/master/docs/
markdown_extensions:
  - meta
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.keys
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

# extra_javascript:

nav:
- 主页: index.md
- 使用条款: 
  - terms-of-use.md
  - service/imagehost/imghost-rules.md

- 图片托管:
  - service/imagehost/imghost.md
  - service/imagehost/imghost-tutorial.md

- 服务接口:
  - service/api/BiliRoaming.md
  - service/api/ADH.md

- 标签: tags.md